# Generated by Django 2.2.8 on 2019-12-21 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('familyName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('regDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
