# Generated by Django 2.2.8 on 2019-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdb',
            name='privLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
