# Generated by Django 2.2.8 on 2019-12-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20191221_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='privLevel',
            field=models.CharField(max_length=2),
        ),
    ]
