# Generated by Django 2.2.8 on 2019-12-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0006_auto_20191222_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='password',
            field=models.BinaryField(null=True),
        ),
    ]
