# Generated by Django 2.2.8 on 2019-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0008_auto_20191222_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdb',
            name='salt',
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='password',
            field=models.CharField(max_length=257),
        ),
    ]
