# Generated by Django 2.2.8 on 2019-12-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0011_auto_20191222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='password',
            field=models.BinaryField(),
        ),
    ]
