# Generated by Django 2.2.8 on 2019-12-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0014_tokensdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
                ('expiration_date', models.DateTimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.UsersDB')),
            ],
        ),
        migrations.DeleteModel(
            name='TokensDB',
        ),
    ]
