# Generated by Django 2.2.8 on 2019-12-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0015_auto_20191222_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionDB',
            new_name='SessionsDB',
        ),
    ]
