# Generated by Django 2.2.8 on 2019-12-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0016_auto_20191222_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassResetDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('expiration_date', models.DateTimeField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.UsersDB')),
            ],
        ),
    ]
