# Generated by Django 2.2.8 on 2020-02-17 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0017_passresetdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=512)),
                ('picture', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolemntDeadline_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('eventEnrolmentData', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='privLevel',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolemnt_date', models.DateTimeField()),
                ('eventEnrolmentDataResponse', models.TextField()),
                ('decision', models.SmallIntegerField(default=0)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.Event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.UsersDB')),
            ],
        ),
    ]
