# Generated by Django 2.2.8 on 2020-02-17 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0018_auto_20200217_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventenrolment',
            old_name='eventEnrolmentDataResponse',
            new_name='enrolmentResponse',
        ),
        migrations.AddField(
            model_name='event',
            name='maxNumberOfEnrolment',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='event',
            name='numberOfEnrolment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventenrolment',
            name='enrolemnt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
