# Generated by Django 2.2.8 on 2020-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0019_auto_20200217_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
