# Generated by Django 2.2.8 on 2020-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0022_posts_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='privLevel',
            field=models.IntegerField(default=4),
        ),
    ]
